### ISSUE TITLE
Increase UT for `cli.admin.ceremoy.ceremony`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#115]
### Is your feature request related to a problem? Please describe.

Increase UT for `cli.admin.ceremoy.ceremony` ~100%

### Describe the solution you'd like

Increase UT for `cli.admin.ceremoy.ceremony` ~100%

**Comment by MVrachev** [comment]
We have good coverage in [test_ceremony.py](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/tests/unit/cli/admin/test_ceremony.py) and it won't bring a lot of value adding unit tests covering the same stuff.

Closing for now, if there are arguments against it please leave a message.
