### ISSUE TITLE
Bug: ceremony bootstrap with `--save` doesn't add .json in the files

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#158]
### What happened?

The bootstrap has an option `--save` that adds the metadata files in `metadata` folder.
The files are added without the `.json` extension.

It is not critical once the content of the files is correct.

During the file saving, it would be good to add the extension `.json`

### What steps did you take?

1. `rstuf admin login`
2. `rstuf admin ceremony --bootstrap --save`

Notice inside the local directory the `metadata` folder with files without .json extension

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
This happens inside the `ceremony.py` module.
Have a look at the `ceremony` function: https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/49e2d23a1cd5ffd83bbc412f06812ff66aac9986/repository_service_tuf/cli/admin/ceremony.py#L697

**Comment by muhahahmad68** [comment]
Can I get a proper explanation for what changes I'm to make to the function
?
