### ISSUE TITLE
Rename `rstuf-cli` to `rstuf`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#165]
https://github.com/vmware/repository-service-tuf-cli/blob/ad3183b68913411b3a61655e696ff53078140da2/repository_service_tuf/cli/admin/ceremony.py#L455

**Comment by MVrachev** [comment]
@Rashed-MM I saw you proposed two prs resolving this issue.
Do you plan to fix it with a pr?
Do you need help with preparing your commits and the pr message?
It's good that the commit message and the pr message explain why a change was made. Here are some good recommendations about git commits: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message

**Comment by KAUTH** [comment]
This issue has been mainly covered by https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/76 and will be closed after https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/292
