### ISSUE TITLE
Add UT  for ``cli.admin.ceremony._load_key ``

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#17]
Add UT to the function  `kaprien.admin.ceremony. _load_key `

Hint: monkeypatch the `import_ed25519_privatekey_from_file`

**Comment by juniorlpa** [comment]
I'll be working on this issue.

**Comment by MVrachev** [comment]
This issue can be considered closed as we have added tests for `_load_key` in this big commit: https://github.com/repository-service-tuf/repository-service-tuf-cli/commit/a25ce0b9145646e8845daa907d11301259d1a9cc
