### ISSUE TITLE
Refactoring enum types in `api_client.py`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#197]
From what I know the enum types should be named as constants with all upper case.
This is also supported by the python docs on enums:
https://docs.python.org/3/library/enum.html
Do you think it's worth discussing in another issue?

_Originally posted by @MVrachev in https://github.com/vmware/repository-service-tuf-cli/pull/195#discussion_r1101545206_

**Comment by MVrachev** [comment]
I think we can close this issue as it's the same as #442 which was closed by #443.
