### ISSUE TITLE
Bug: optional dependencies (sqlalchemy and psycopg2)

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#204]
### What happened?

PR #195 added the feature `admin import-targets` to the CLI
This feature introduced two new dependencies `sqlalchemy` and `psycopg2` as optional, but they are required to any kind of `rstuf` command

It happens because the rstuf CLI is module, however in the the `cli.__init__.py` we import all submodules.
https://github.com/vmware/repository-service-tuf-cli/blob/b8ca50dbc755791c1bc7ecf1d741152192c6c943/repository_service_tuf/cli/__init__.py#L55-L59
what imports the `sqlalchemy` and `psycopg` on top from `cli.admin.import_targets.py`
https://github.com/vmware/repository-service-tuf-cli/blob/b8ca50dbc755791c1bc7ecf1d741152192c6c943/repository_service_tuf/cli/admin/import_targets.py#L7-L8

It causes the error
```log
ModuleNotFoundError: No module named 'sqlalchemy'
```

Linked o issues
- https://github.com/vmware/repository-service-tuf/issues/246
- https://github.com/vmware/repository-service-tuf/issues/245

### What steps did you take?

1. Clone the RSTUF CLI
2. Install the development version of RSTUF CLI (`pip install -e .`
3. Run any CLI command `rstuf admin login`

### What behavior did you expect?

The command `import-targets` is used most for specific installations, and the SQLAlchemy should be optional and raised to the user if they want to use this command.

We should move the import inside the `def import_targets`

https://github.com/vmware/repository-service-tuf-cli/blob/b8ca50dbc755791c1bc7ecf1d741152192c6c943/repository_service_tuf/cli/admin/import_targets.py#L132

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KAUTH** [comment]
This was fixed by https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/206.
