### ISSUE TITLE
Add UT for ``helpers.tuf.initialize_metadata``

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#21]
- Implement the UT
Bonus: Remove the duplicated code in the initialize_metadata

**Comment by MVrachev** [comment]
We can close this issue as tests were added in: https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/232/commits/7dd4c63b356ad41b9f06c06c38f077a8f218e1fe
