### ISSUE TITLE
Python version mismatch

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#281]
### What happened?

Since version 1.1.1a3, the RSTUF CLI required Python 3.10 or above.

It is not clear and confuses the users. 

We need changes in our documentation and our `pyproject.toml`.

The second option is replacing the `match` condition in the key management feature with the `if` statement. 

### What steps did you take?

- check pypi repository service for tuf web https://pypi.org/project/repository-service-tuf/#data

### What behavior did you expect?

Compatibility aligment

### Relevant log output

```shell
https://cloud-native.slack.com/archives/C047L55314N/p1683251898407269
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepNet-Chirag** [comment]
Can I work on this Issue?

**Comment by kairoaraujo** [comment]
Hi @deepNet-Chira, yes! I'm signing the issue to you. 🎉

**Comment by deepNet-Chirag** [comment]
Pull request is send on the issue! Let me know if something is came wrong..

**Comment by kairoaraujo** [comment]
Closed by PR
- #282
