### ISSUE TITLE
Task: Add distributed async  (`metadata sign`) and include support to `ceremony` 

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#294]
### What is the task about?

This task is to support distributed async support for the user using the CLI.

This task must be implemented on top of
- https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/222
- https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/290

### Ceremony (`rstuf admin ceremony`)

The current ceremony asks the user to load all Online and Root keys.
- The online key should be required to load using a private key and password, only give the [key info](https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/290)

```shell
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                   STEP 2: Load the Online Key                                    ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


                                           The Online Key                                           

The online key is the same one provided to the Repository Service for TUF Workers (RSTUF Worker).   
This key is responsible for signing the snapshot, timestamp, targets, and delegated targets (hash   
bin) roles.                                                                                         

The RSTUF Worker uses this key during the process of managing the metadata.                         

Note: the ceremony process won't show any password or key content.                                  

Choose 1/1 ONLINE key type [ed25519/ecdsa/rsa] (ed25519): 
Enter 1/1 the ONLINE`s key id: f7a6872f297634219a80141caa2ec9ae8802098b07b67963272603e36cc19fd8
Enter 1/1 the ONLINE`s public key hash: 9fe7ddccb75b977a041424a1fdc142e01be4abab918dc4c611fbfe4a3360a9a8
[Optional] Give a name/tag to the key: online key v1
✅ Key 1/1 Verified
```
The Root key(s) should be complete optional:
- The first key must to be loaded to initially sign the metatada.
- The user can load the remaining key(s) or give the key(s) info for late signing

Example: Root with 3 keys and threshold 2

```shell
Ready to start loading the root keys? Passwords will be required for keys [y/n]: y
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                      STEP 3: Load Root Keys                                      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


                                             Root Keys                                              

The keys must have a password, and the file must be accessible.                                     

Depending on the organization, each key has an owner, and each owner should insert their password   
personally.                                                                                         

Note: the ceremony process won't show any password or key content.                                  

Load 1/3 root for signing (key file path and password required)? [y/n]: y

Choose 1/3 root key type [ed25519/ecdsa/rsa] (ed25519): 
Enter 1/3 the root`s private key path: tests/files/key_storage/JanisJoplin.key
Enter 1/3 the root`s private key password: 
[Optional] Give a name/tag to the key: Janis Joplin
✅ Key 1/3 Verified

Load 2/3 root for signing (key file path and password required)? [y/n]: n

Choose 2/3 root key type [ed25519/ecdsa/rsa] (ed25519): 
Enter 2/3 the root`s key id: 800dfb5a1982b82b7893e58035e19f414f553fc08cbb1130cfbae302a7b7fee5
Enter 2/3 the root`s public key hash: 7098f769f6ab8502b50f3b58686b8a042d5d3bb75d8b3a48a2fcbc15a0223501
[Optional] Give a name/tag to the key: Jimi Hendrix
✅ Key 2/3 Verified

Load 3/3 root for signing (key file path and password required)? [y/n]: n

Choose 3/3 root key type [ed25519/ecdsa/rsa] (ed25519):                                                                 
Enter 3/3 the root`s key id: 5f6689eb887a7acd68ec879360e0bced79d27469db6f75e16d834e4aecb35860
Enter 3/3 the root`s public key hash: 47778ad170d60b9b99636e5d484f8aac2dcd729312225e69767e2584945f98d2
[Optional] Give a name/tag to the key: Joe Cocker
✅ Key 3/3 Verified
```

The bootstrap will finish when the role metadata is signed by key 2 or 3.

### Metadata Sign (`rstuf admin metadata sign`)

- It will retrieve from the RSTUF API (`GET` `/api/v1/metadata/sign`) all role metadatas in signing state
- The user must choose one role to sign
- The user must load one of expected keys
- The CLI will validate the key based in the `key id`
- The CLI will add the signature and send only the signature part to RSTUF API (`POST` `/api/v1/metadata/sing`)
- The CLI will retrieve the status of the signing

```shell
❯ rstuf admin metadata sign
RSTUF API URL address: http://127.0.0.1

Choose a role to sign [root]: root

Choose a key to load [Jimi Hendrix/Joe Cocker]: Joe COcker
Please select one of the available options

Choose a key to load [Jimi Hendrix/Joe Cocker]: Joe Cocker

Choose Joe Cocker key type [ed25519/ecdsa/rsa] (ed25519): 
Enter Joe Cocker`s private key path: tests/files/JoeCocker.key
Enter Joe Cocker`s private key password: 

Signature root added.
```

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/327

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I have a working prototype with Ceremony and Sign available here
- https://github.com/kairoaraujo/repository-service-tuf-cli/tree/distributed_async_sign/repository_service_tuf/cli/admin

**Comment by lukpueh** [comment]
Cool stuff, @kairoaraujo! I think this should work. Although, the UX of copy-pasting key values from one cli tool into another interactive cli tool could be improved. For the "key file" use case, I think it would be nice to just ask the user to provide the path to either private or public key. secure-systems-lab/securesystemslib#604 will add new API, which will make this a lot easier. No need to wait until this lands, but we should keep an eye on those developments for future improvements.

**Comment by kairoaraujo** [comment]
> Cool stuff, @kairoaraujo! I think this should work. Although, the UX of copy-pasting key values from one cli tool into another interactive cli tool could be improved. For the "key file" use case, I think it would be nice to just ask the user to provide the path to either private or public key. [secure-systems-lab/securesystemslib#604](https://github.com/secure-systems-lab/securesystemslib/pull/604) will add new API, which will make this a lot easier. No need to wait until this lands, but we should keep an eye on those developments for future improvements.

This idea is also excellent.

What about supporting multiple ways to do it?

- The user can load the public key -- IMHO, I don't think someone would like to share the private key.
- The user can enter the information

It is challenging to choose one use case because, at that point, the user will have to define a trusted way to exchange their public key files or the public key information, outside RSTUF scope*.

The user can exchange the files using a trusted volume or attach them to an email message, but maybe they cannot attach this kind of file and want to share the public key information (id).
Even sending files to each other will have the requirement to copy/save files somewhere, so the "copy-pasting" will maybe change a bit but still be required somehow.

* It is outside the RSTUF scope unless we work to have a signing storage key, but we must have a way to identify key owner's safety -- maybe a future feature.

**Comment by lukpueh** [comment]
> IMHO, I don't think someone would like to share the private key.

Yes, the private key load option only makes sense for the user's own key.  

> It is challenging to choose one use case because, at that point, the user will have to define a trusted way to exchange their public key files or the public key information, outside RSTUF scope*.

Agreed, this is the tricky part. But it's tricky regardless of whether the cli loads the key from a pub key file, or asks the user to paste it, right?

> It is outside the RSTUF scope unless we work to have a signing storage key, but we must have a way to identify key owner's safety -- maybe a future feature.

Yes. That would work. But then the signing key storage is the root of trust. How do you protect that?

**Comment by kairoaraujo** [comment]
> Agreed, this is the tricky part. But it's tricky regardless of whether the cli loads the key from a pub key file, or asks the user to paste it, right?

We can work on the UX for it.
We could ask the user for the public key and the user has the freedom to give the public key file or the keyid for example.
From the string, we can determine if it is a file or checking the hash is a keyid

> > It is outside the RSTUF scope unless we work to have a signing storage key, but we must have a way to identify key owner's safety -- maybe a future feature.
> 
> Yes. That would work. But then the signing key storage is the root of trust. How do you protect that?

This is the same question I have, how to protect it? I think it could be a nice feature but in the future 🤣
