### ISSUE TITLE
Task: Add documentation in the Guide for "metadata update"

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#317]
### What is the task about?

Add documentation for[ "metadata update" in the Guide, usage chapter.](https://repository-service-tuf.readthedocs.io/en/v0.1.0b1/guide/general/usage.html#metadata-update)

The idea is to create a short explanation of the feature and the usage
Do not give too many details, but a simple use case example and how to proceed. See the [import targets section](https://github.com/repository-service-tuf/repository-service-tuf/blob/main/docs/source/guide/general/usage.rst#importing-existing-targets) as an example.
The details about usage can be pointed to the CLI documentation section of repository-service-for-tuf

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
@kairoaraujo maybe we do want to wait with this issue until we have distributed metadata signing implemented.
Do you agree?

**Comment by kairoaraujo** [comment]
The feature is available, and having the documentation will require only an update for DAS (but I think the doc is mostly the same.
But I'm just leaving it as your call.
