### ISSUE TITLE
Task: Add distributed async support to `metadata update`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#326]
### What is the task about?

This task is to support distributed async support for the user using the CLI.

This task must be implemented on top of
- #222
- #290
- #294 

`rstuf admin metadata update` needs to support

- Use a single private key to start the process
- The user can inform all the public keys required for signing
- The signature will happen distributed and asynchronous using the `rstuf admin metadata sign` implemented by #294

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/327

### References

- #294 the bootstrap process (`rstuf admin ceremony`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
Here it's important how the authorization part should happen.
Currently, when we do metadata update with full signing, we expect at least threshold number of keys from current root to be loaded.
Now, we cannot do that as curent root can be signed from people around the world.
What I suggest is that we change what `GET /api/v1/metadata/sign` returns to include information for the actual keys that are expected to sign the metadata.
They will be presented by their keyid (we don't need to send full key information and given that for aws keys it's likely we are going to change the public key value of the key to securesystemslib pub key value we don't want to show that).
Finally, when a user calls `POST /api/v1/metadata/sign` and gives signature of the metadata and keyid we would make sure that this keyid is from the list of keyids we allow for signing.

The reason why this will help is that when a user asks for `GET /api/v1/metadata/sign` we would return only those keyids from current root that are not loaded + the additional keys required to verify the new root.json.

What do you think of that idea @lukpueh, @KAUTH and @kairoaraujo?

**Comment by MVrachev** [comment]
We do support DAS with our new CLI.
