### ISSUE TITLE
Feature: Custom timeout for Ceremony Bootstrap

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#328]
### What is the task about?

This task is a feature implementation on the CLI to support a custom timeout.
A request to the RSTUF API does the Bootstrap.
The request is done to the `/api/v1/bootstrap` using the method `POST` and it is used by `rstuf admin ceremony --bootstrap`
The endpoint supports a custom timeout (default is 300 seconds).

This issue is about providing the timeout parameter in the CLI when the user uses `-b/—bootstrap`.

### References

API Documentation
- https://repository-service-tuf.github.io/repository-service-tuf-api/#/v1/post_api_v1_bootstrap__post

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by primuzer** [comment]
@kairoaraujo I have submitted PR plz review it

**Comment by kairoaraujo** [comment]
> @kairoaraujo I have submitted PR plz review it
> [#329 (comment)](https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/329#issue-1829974066)

Thank you @primuzer, I just did it 👍

**Comment by MVrachev** [comment]
A future contributor can take the advices of @kairoaraujo here:
https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/329#pullrequestreview-1556648475
