### ISSUE TITLE
Enhancement: Improve task status verification

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#339]
This issue is about improving the task status.

https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/01511b781d11cda24fcac3a231a1cc14d02ef698/repository_service_tuf/helpers/api_client.py#L148

Not only using the task `state`, but also the 
https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/01511b781d11cda24fcac3a231a1cc14d02ef698/repository_service_tuf/helpers/api_client.py#L169 but extend and use the task status.

For that, the below task must be implemented:
- [x] https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/315

**Comment by KAUTH** [comment]
Hey @kairoaraujo could you help me better understand the goal of this task?

> Not only using the task `state`, but also the `status`.

- Why do we want to use the `status`?
    - the `status` is based on Celery status (`status` enum in the worker), so I assume you might want to use the status to avoid being tied to the specific backend? Is this the reason for this GH task?
- If we _do_ want to use `status`, how do you think it would help in addition to the `state` and not just the `status`?
- Last, the only status information I could find was `status="Task finished."`.
I think if we use it we should make it more clear in the worker (and the api), for example create an enum (right now it's a string in `ResultDetails` in the worker).
Also, in the rstuf-api, in the `TasksData` class, `result` is `Optional[Any]`, so the structure/possible-response is not clear neither from the API docs.

**Comment by kairoaraujo** [comment]
> Hey @kairoaraujo could you help me better understand the goal of this task?
> 
> > Not only using the task `state`, but also the `status`.
> 
> * Why do we want to use the `status`?
>   
>   * the `status` is based on Celery status (`status` enum in the worker), so I assume you might want to use the status to avoid being tied to the specific backend (Celery)? Is this the reason for this GH task?

The `status` is not the Celery. It is task `state`
From this, we identify the top [level state: `SUCCESS`, `FAILURE`, `STARTED`, ...](https://docs.celeryq.dev/en/stable/userguide/tasks.html#built-in-states)


> * If we _do_ want to use `status`, how do you think it would help in addition to the `state` and not just the `status`?

So, the `state` gives us the information about the "task as a process". Os it `STARTED`? Is it finished (`SUCCESS`)?, Is it `FAILED`?

So, if a task process (`state`) is finished (`SUCCESS`), it can have a status `False`, meaning the task could perform what was requested. For example, you requested a metadata update, [but the current RSTUF state doesn't allow it](https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/f55848ef8c88bfc7d9fdb1aca03c41540faf3e68/repository_service_tuf_worker/repository.py#L1228-L1235).

It gives the following information to the user:
- The task was processed
- There is an error which must be handled.

The user can take decisions from there.


> * Last, the status information I could find was conflicting. In some cases we use `status="Task finished."` (see [here](https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/175f26f07d1831221adeb412ad3dbd4f207e29b9/repository_service_tuf_worker/repository.py#L469)), while in others the celery tasks status (see [here](https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/175f26f07d1831221adeb412ad3dbd4f207e29b9/repository_service_tuf_worker/repository.py#L573)).
>   I think if we use it we should make it more clear in the worker (and the api), for example create an enum (right now it's a string in `ResultDetails` in the worker).
>   Also, in the rstuf-api, in the `TasksData` class, `result` is `Optional[Any]`, so the structure/possible-response is not clear neither from the API docs.

I think the confusion is the blobs you sent were before we standardized the [task results](https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/main/repository_service_tuf_worker/repository.py#L94)
- https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/349



`state`: From Celery
`status`: Boolean


See also that we want to standardize when we have errors.
- https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/351

**Comment by KAUTH** [comment]
Thanks for the detailed explanation @kairoaraujo! I was indeed looking at non-standardized old versions of the api and worker :see_no_evil:
