### ISSUE TITLE
Align  `--upload-server` in ceremony to match `--api-url` of `rstuf token`

### ISSUE THREAD

**Issue by KAUTH** [repository-service-tuf/repository-service-tuf-cli#347]
> Good point! In the ceremony we have `--upload-server`, do you think we should perhaps change this to `--api-url` in the future to align?

_Originally posted by @KAUTH in https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/344#discussion_r1293986687_

**Comment by MVrachev** [comment]
Do we still have this issue considering we don't have authorization commands anymore such as `rstuf token` @KAUTH?

**Comment by KAUTH** [comment]
> Do we still have this issue considering we don't have authorization commands anymore such as `rstuf token` @KAUTH?

The specific point has been fixed, not because we don't have authorization anymore but it has been adjusted from `--upload-server` to `--api-server `. I did find though one point we did not update it in the docs, so see linked PR.
