### ISSUE TITLE
Task: add information about pending signatures during a DAS Bootstrap ceremony

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-cli#355]
### What is the task about?

Add information to the user about pending signatures during a DAS Bootstrap ceremony.
I imagine this will be at the end of the bootstrap ceremony so that the user understands that:
1. the root metadata is not yet considered trustworthy
2. X amount of signatures are needed to finish the bootstrap process

This is important as there are multiple questions and steps in the bootstrap ceremony and it's possible to forget what was the threshold and how many keys were actually loaded and the user can be left with the impression he has finished with the bootstrap ceremony.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivanayov** [comment]
Can I work on this?
