### ISSUE TITLE
Task: Create a way to delete signing process using CLI

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#370]
### What is the task about?

The latest RSTUF API (v0.7.0b1) has introduced an endpoint to delete a signing process.
If there is a signing process (e.g.: Bootstrap -- signing root) the RSTUF admin can stop (delete) this process.

For this, the user needs to send a `DELETE` to `/api/v1/metadata/sign` using the payload which contains the metadata name, as is [documented here](https://repository-service-tuf.github.io/repository-service-tuf-api/#/v1/delete_sign_api_v1_metadata_sign_delete).

The current CLI implements the signing process using `rstuf admin metadata sign`
It would be interesting to have an easy way for the CLI user to also delete the metadata signing process.

Suggestion:
`rstuf admin metadata sign --delete`

1. Look for the existent metadata signing (it is already implemented)
2. Ask the user if wants to delete
3. Creates the payload
4. Send the request `DELETE` to `/api/v1/metadata/sign`

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/327#issuecomment-1560574181

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivanayov** [comment]
Can I work on this?
