### ISSUE TITLE
Task: Bandit fails with API client errors

### ISSUE THREAD

**Issue by ivanayov** [repository-service-tuf/repository-service-tuf-cli#382]
### What is the task about?

`make precommit` fails on bandit (v1.7.5) .

If those are new vulnerabilities, we could address them.

```

Test results:
>> Issue: [B113:request_without_timeout] Requests call without timeout
   Severity: Medium   Confidence: Low
   CWE: CWE-400 (https://cwe.mitre.org/data/definitions/400.html)
   More Info: https://bandit.readthedocs.io/en/0.0.0/plugins/b113_request_without_timeout.html
   Location: repository_service_tuf/helpers/api_client.py:50:23
49	        if method == Methods.get:
50	            response = requests.get(
51	                f"{server}/{url}", json=payload, data=data, headers=headers
52	            )
53	

--------------------------------------------------
>> Issue: [B113:request_without_timeout] Requests call without timeout
   Severity: Medium   Confidence: Low
   CWE: CWE-400 (https://cwe.mitre.org/data/definitions/400.html)
   More Info: https://bandit.readthedocs.io/en/0.0.0/plugins/b113_request_without_timeout.html
   Location: repository_service_tuf/helpers/api_client.py:55:23
54	        elif method == Methods.post:
55	            response = requests.post(
56	                f"{server}/{url}", json=payload, data=data, headers=headers
57	            )
58	

--------------------------------------------------
>> Issue: [B113:request_without_timeout] Requests call without timeout
   Severity: Medium   Confidence: Low
   CWE: CWE-400 (https://cwe.mitre.org/data/definitions/400.html)
   More Info: https://bandit.readthedocs.io/en/0.0.0/plugins/b113_request_without_timeout.html
   Location: repository_service_tuf/helpers/api_client.py:279:19
278	        console.print(f"Fetching file {file_uri}")
279	        response = requests.get(file_uri)
280	        if response.status_code != 200:

--------------------------------------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Hi @KAUTH, I need your expertise here 😄 

Every time we run `make precommit`, I notice it updates the dependencies.
It can cause confusion among contributors. :(

**Comment by KAUTH** [comment]
> Hi @KAUTH, I need your expertise here 😄
> 
> Every time we run `make precommit`, I notice it updates the dependencies. It can cause confusion among contributors. :(

Hm :thinking:, this is actually a sign of an other issue. We should check that the pre-commit hooks that we use have the latest versions, otherwise tools like `bandit` will not have the latest updates when we run the against our code. This could be a different workflow that updates them periodically, like `update-python-deps.yml`, but since we are not updating dependencies that are part of the source code, it's also fine to do it along with the typical CI checks.

Here is my PR proposal for this.
