### ISSUE TITLE
Task: Add more info to repository details

### ISSUE THREAD

**Issue by KAUTH** [repository-service-tuf/repository-service-tuf-cli#392]
### What is the task about?

- Add the package's [PyPI link](https://pypi.org/project/repository-service-tuf/) to repository details
Example:
![image](https://github.com/repository-service-tuf/repository-service-tuf-cli/assets/15343142/74c4fca1-99f9-4857-9800-a131c35aa71e)

- Add [Topics](https://github.blog/2017-01-31-introducing-topics/#:~:text=Topics%20are%20labels%20that%20create,projects%20by%20type%2C%20technology%2C%E2%80%A6) so that we make the project more easily discoverable

Suggested topics: tuf, cli, python, security, supply-chain, or also use some of what's on https://github.com/theupdateframework/python-tuf.
Additionally add the `hacktoberfest` label for October 🎃 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KAUTH** [comment]
@kairoaraujo should I assign this to you, since I think you are the only one that can edit this probably?

**Comment by kairoaraujo** [comment]
Just did it @KAUTH

**Comment by KAUTH** [comment]
> Just did it @KAUTH

Awesome!
