### ISSUE TITLE
Task: Remove authn/z and token feature from `rstuf` CLI

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#406]
### What is the task about?

This task is about removing all the features for authentication and authorization from the `rstuf` command line interface.

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/491

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
Here are some items we have discussed in a meeting:
- remove from https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/repository_service_tuf/cli/__init__.py:
    - `--auth`
    - `--token`
- Remove tests for commands using `--auth` and `--token`
- Simplify:
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/repository_service_tuf/cli/__init__.py#L112C41-L112C66
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/repository_service_tuf/cli/__init__.py#L105
- Remove commands:
    - `admin login`
    - `admin token`
    - tests for those commands
- From helpers:
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/repository_service_tuf/helpers/api_client.py#L87
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/repository_service_tuf/helpers/api_client.py#L113
- keep `settings.ini` in the local repo | we will use it in the future
- update READTHEDOSC diagram:
    - remove https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/docs/diagrams/repository-service-tuf-cli-C3.puml#L54
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/docs/diagrams/repository-service-tuf-cli-C3.puml#L85
    - https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/afd0cb1df93541b4326c80e560e37840f1f4a7c2/docs/diagrams/repository-service-tuf-cli-C3.puml#L86
- remove all references from `guide` docs and `dev guide` docs and `from comments` of:
    - auth
    - token
    - authorization
    - login
