### ISSUE TITLE
Task: Update the CLI command `rstuf admin metadata sign --delete`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#409]
### What is the task about?

Update the RSTUF CLI command `rstuf admin metadata sign --delete` to use the new `/api/v1/sign/delete` endpoint and method post.

Task required:
- https://github.com/repository-service-tuf/repository-service-tuf-api/issues/464

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf-api/issues/455

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivanayov** [comment]
I can work on that

**Comment by kairoaraujo** [comment]
@ivanayov,

The changes on API were merged. We will need to release the CLI. :) 
Thank you.
