### ISSUE TITLE
Task: Migrate `admin` -> `admin-legacy` | `admin2` -> `admin`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#562]
### What is the task about?

It requires the below task complete:
- [x] https://github.com/repository-service-tuf/repository-service-tuf/issues/686

This FT will keep monitoring for all changes in the admin2 as it will have new changes, but the functionality of ceremony, sign, and metadata update is consistent.

This task will migrate:
- `admin` -> `admin-legacy`
- `admin2` -> `admin`
- Update all documentation in `docs/guide`
- Add a disclaimer in the `admin-legacy` will be removed and the issue [with online key rotation](https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/491)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
@kairoaraujo I think the only thing left kere is a disclaimer that `admin-legacy` will be removed soon and recommend the new admin?
