### ISSUE TITLE
Improve: Create SECURITY_INSIGHTS.yml

### ISSUE THREAD

**Issue by Danajoyluck** [repository-service-tuf/repository-service-tuf-cli#654]
### What do you want to share with us?

Talked to Kairo about this as part of the [security baseline pilot adoption](https://github.com/ossf/security-baseline?tab=readme-ov-file#openssf-security-baseline-adoption-pilot-projects).

Create SECURITY_INSIGHTS.yml at the root of the repository and ensure [schema](https://github.com/ossf/security-insights-spec/blob/main/security-insights-schema.yaml) compliance.

The insights SHALL provide header information, project lifecycle, and contributing policy.

Example SECURITY_INSIGHTS.yml :
OpenSSF: [GUAC](https://github.com/guacsec/guac/blob/main/SECURITY-INSIGHTS.yml), [Security Insight](https://github.com/ossf/security-insights-spec/blob/main/SECURITY-INSIGHTS.yml)

### References

https://github.com/ossf/tac/blob/main/process/security_baseline.md#security-baseline---once-incubating

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Hi @Danajoyluck,
I opened the issue in the RSTUF umbrella as this applies to all components (including RSTUF CLI).
https://github.com/repository-service-tuf/repository-service-tuf/issues/789
Thank you for your contribution.
