### ISSUE TITLE
Bug: Verify if the Sigstore `identity` is an email

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#671]
### What happened?

While using RSTUF CLI, we don't verify if the given identity is an email address or, at least, if it is empty.
<img width="756" alt="Screenshot 2024-08-18 at 20 26 09" src="https://github.com/user-attachments/assets/4bd0a1f2-9d19-4194-afd8-beb33839e9c9">

### What steps did you take?

<img width="756" alt="Screenshot 2024-08-18 at 20 26 09" src="https://github.com/user-attachments/assets/4bd0a1f2-9d19-4194-afd8-beb33839e9c9">

### What behavior did you expect?

Please don't accept empty entries or, even better, if the identity isn't in an email format.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukulbindal** [comment]
@kairoaraujo can you please assign this issue to me

**Comment by kairoaraujo** [comment]
Hi @mukulbindal,

I appreciate your interest in contributing to RSTUF.
The issue has been assigned, so let me know if you need any guidance.

**Comment by mukulbindal** [comment]
@kairoaraujo Thank you for assigning me this issue. Requesting you to review the Pull Request. As it's my first time contributing to this repo, kindly bear with me.
