### ISSUE TITLE
Other: CLI UX improvement

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#691]
### What do you want to share with us?

We currently ask what is the Sigstore signing provider like this
```shell
> https://github.com/login/oauth
  https://login.microsoft.com
  https://accounts.google.com
```

We could use the names like:
```shell
> GitHub
  Google
  Microsoft
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukulbindal** [comment]
Hi @kairoaraujo can I work on this please

**Comment by kairoaraujo** [comment]
Sure thing, @mukulbindal.
Thank you for your contribution. It is very welcome!

**Comment by mukulbindal** [comment]
Hi @kairoaraujo could you please guide me on how to replicate this in my local machine.
